from deepeval import assert_test
from deepeval.metrics import (
    AnswerRelevancyMetric # If your installed version uses this path, or GEval
)
from deepeval.test_case import LLMTestCase


def test_customer_support_relevance():
    test_case = LLMTestCase(
        input="How do I reset my password?",
        actual_output="You can reset your password by clicking on 'Forgot Password' on the login screen."
    )
    metric = AnswerRelevancyMetric(threshold=0.7)
    assert_test(test_case, [metric])

    # def test_customer_support_relevance(): 
#     Standard Pytest 
#     test function 
#     definition.

# test_case = LLMTestCase(...): 
#     Instantiates the test 
#     case object combining 
#     the prompt and response.

# input="...": 
#     Defines the prompt 
#     sent to the AI model.

# actual_output="...": 
#     Defines the response 
#     generated by the system.

# metric = AnswerRelevanceMetric(threshold=0.7): 
#     Initializes the relevance 
#     metric with a 70% (0.7) 
#     passing threshold.

# assert_test(test_case, [metric]): 
#     Executes the evaluation 
#     by passing the test case 
#     and metrics into DeepEval.